sublimelsp/lsp_utils

.gitignore, st3/lsp_utils/server_npm_resource.py
The idea is to then have a check like this one in `def config`  in LSP-* packages:
```py
if not server.ready:
return read_client_config(self.name, {
'enabled': False,
'languages': [{}],
})
```
=> Expose "ready" property for checking if server installed successfully

st3/lsp_utils/server_npm_resource.py
Just compare the file contents of each file, and if they don't match remove the folder.
I think comparing string is more performant
than parsing it to json and then comparing the versions.
This means that we delete the version from the package.json file.
```diff
{
"name": "typescript-language-server",
-  "version": "0.4.0",
"dependencies": {
"typescript": "3.8.3",
"typescript-language-server": "0.4.0"
}
}
```
=> Compare the file contents of each file, withouth parsing it to JSON

st3/lsp_utils/__init__.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/server_npm_resource.py
Adds `NpmClientHandler` export that at minimium requires only
overriding PACKAGE_NAME, SERVER_DIRECTORY and SERVER_BINARY_PATH class
attributes.
=> Create NpmClientHandler to simplify NPM handler creation

st3/lsp_utils/__init__.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/npm_client_handler_v2.py, st3/lsp_utils/server_npm_resource.py
Use the new API in ST4. Technically nothing should change for existing plugins but it will allow them to use new features like access to Session.
It's still using ServerNpmResource for installing dependency rather than using only new API as new API is not async yet so it would provide worse experience.
=> Create separate handler for the new LSP API

st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/npm_client_handler_v2.py, st3/lsp_utils/server_npm_resource.py
A plugin can define a class method like:
@classmethod
def minimum_node_version(cls) -> Tuple[int, int, int]:
return (10, 0, 0)
to specify the minimum Node version required by the server. By default
the minimum is v8.
Relates to https://github.com/sublimelsp/LSP-pyright/issues/15
=> Add support for specifying minimum Node version

st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/npm_client_handler_v2.py, st3/lsp_utils/server_npm_resource.py
A large number of files within directories that ST considers part of the
"catalog" make ST less performant, making catalog queries and ST startup
take a longer time.
Introduced a class method that plugins can override to request being
installed in the "Data/LSP-servers/[PackageName]" directory which is
part of the user settings but not inside directories that are part of
the "catalog".
This needs to be done in an opt-in way instead of just switching directly
in lsp_utils as we need to allow the update flow to run for dependent
packages so that the "plugin_unload" event clears out the old directory.
=> Add support for installing servers outside of ST "catalog"

st3/lsp_utils/helpers.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/npm_client_handler_v2.py, st3/lsp_utils/server_npm_resource.py
Instead of creating extra thread when installing server in ST4,
use "AbstractPlugin.needs_update_or_installation" and co.
The advantages are:
- no extra threads
- lazy installation - only starts when associated file is opened
- does not require ST restart after server was installed
Also, call "(un)register_plugin" as recommended by AbstractPlugin API.
=> Make ST4 handler use AbstractPlugin installation flow

docs/source/client_handlers.rst, docs/source/server_resource_handlers.rst, st3/lsp_utils/__init__.py, st3/lsp_utils/_client_handler/abstract_plugin.py, st3/lsp_utils/_client_handler/interface.py, st3/lsp_utils/_client_handler/language_handler.py, st3/lsp_utils/generic_client_handler.py, st3/lsp_utils/helpers.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/pip_client_handler.py, st3/lsp_utils/server_pip_resource.py
This is a client handler and server resource implementation that manages a pip-based server from dependencies provided through "requirements.txt" file.
There is no support for overriding versions of dependencies because I don't see a need for it.
Also:
- remote "GenericClientHandler.get_storage_path()" API and just use  "GenericClientHanlder.storage_path()" instead which is provided by both AbstractPlugin and LanguageHandler
- Document storage_path() and package_storage() of GenericClientHandler
=> Add PipClientHandler implementation

docs/source/client_handlers.rst, st3/lsp_utils/__init__.py
Not exporting from the main `lsp_utils` export as importing the class
but not using it anywhere would trigger an error when LSP would try
to call class methods of such class.
=> Require importing PipClientHandler from its file

st3/lsp_utils/__init__.py, st3/lsp_utils/activity_indicator.py
A main-thread variant of the `ActivityIndicator` from `sublime_lib`.
Relates to https://github.com/sublimelsp/LSP-pyright/issues/36
=> Add ActivityIndicator that works on the main thread

st3/lsp_utils/activity_indicator.py
If `stop()` is called between `sublime.set_timeout(self._tick, self.interval)` and `_update()` (there is a 100ms interval between these two calls), `self._target.clear()` will be called first from `stop()` and then `self._target.set(self._render(self._ticks))` from `_update()`.
This results in the message gets "stucked" in the status bar.
---
Fixes https://github.com/sublimelsp/lsp_utils/issues/48
=> fix: activity indicator still shows after being stopped

lsp_utils.sublime-commands, lsp_utils.sublime-settings, st3/lsp_utils/api_wrapper_interface.py, st3/lsp_utils/node_distribution.py, st3/lsp_utils/node_runtime.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/server_npm_resource.py, sublime-package.json
Needs to be tested on Linux. On Mac extracting `*.tar.xz` fails in Python 3.3 and I needed to switch to `*.tar.gz`. The same might be necessary for Linux.
On ST3 Node installation happens on the main thread so that's not ideal.
=> feat: ask to install local node runtime if not available in PATH

st3/lsp_utils/_client_handler/abstract_plugin.py, st3/lsp_utils/_client_handler/language_handler.py, st3/lsp_utils/_util/__init__.py, st3/lsp_utils/_util/weak_method.py
ApiWrapper receives a weak reference to the plugin instance to break the
cyclic dependency.
The handler passed to ApiWrapper methods that create API handlers
is only referenced weakly.
Fixes #55
=> Fix issues with cyclic references and plugin instances not being GC'ed

st3/lsp_utils/__init__.py, st3/lsp_utils/node_runtime.py, st3/lsp_utils/server_npm_resource.py
Moved from ServerNpmResource to NodeRuntime to be able to re-use NodeRuntime for other purposes in the future.
=> refactor: move node runtime resolving to NodeRuntime

st3/lsp_utils/node_runtime.py, st3/lsp_utils/server_npm_resource.py
Before the server installation we'll create a marker file that will
only be removed on successful installation. So if the installation is
interrupted by closing ST or otherwise we'll not end up with a broken
installation that will then require re-installing the plugin.
=> Make npm server install more robust

st3/lsp_utils/_client_handler/abstract_plugin.py, st3/lsp_utils/_client_handler/interface.py, st3/lsp_utils/generic_client_handler.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/pip_client_handler.py
=> Ensure that local node runtime and python bindir are in the PATH

st3/lsp_utils/server_pip_resource.py
The logic was quite broken.
- there was no checking if new requirement was added
- comparing pylsp version didn't work because it's listed as `python-lsp-server[all]` in requirements.txt but in `pip freeze` output there are individual modules rather than the `[all]` meta module. Added a hack for that that just removes `[all]` before checking.
=> slightly fix the required/installed requirement comparing

st3/lsp_utils/node_runtime.py, st3/lsp_utils/server_npm_resource.py
In some cases failure to resolve node runtime would only result in
a brief message in the status bar and server not starting. Make the
failure more obvious by raising an exception that will result in
disabling the client and showing an error.
=> Be louder about failing to resolve node runtime

st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/server_npm_resource.py
Some servers, like the new version of stylelint, bundle all dependencies
and don't need to have any dependencies installed.
This is needed because having no dependencies defined results in
no "node_modules" being created and messes up the logic that detects
if the server is installed or not.
=> Add an option to skip "npm install" for npm servers

st3/lsp_utils/_client_handler/abstract_plugin.py, st3/lsp_utils/_client_handler/interface.py, st3/lsp_utils/_client_handler/language_handler.py, st3/lsp_utils/generic_client_handler.py, st3/lsp_utils/npm_client_handler.py
Instead of mutating the actual sublime settings, modify the client
configuration from "can_start".
Also removes the `on_client_configuration_ready` API since nothing
seems to be using it and it's not ideal to use it anyway.
Fixes https://github.com/sublimelsp/LSP/pull/1907#issuecomment-981113099
Fixes #84
=> Don't mutate plugin settings

st3/lsp_utils/node_runtime.py
Time to finally update to the latest Node LTS version since we'll have a package that requires it (https://github.com/sublimelsp/LSP-Grammarly).
Unfortunately we don't have a way to clean old node installations from Cache. We could add a cleanup routine in the future but deleting stuff is always a bit risky.
=> Update bundled Node version to latest LTS version (16)

st3/lsp_utils/server_npm_resource.py
This fixes an issue that would only potentially affect developers working on LSP-* packages.
If someone did an `npm install` in, for example, a local `LSP-pyright/language-server/` repository then lsp_utils would not run `npm install` even after dependency is bumped in `package.json` which means that ST would use old version of the server.
I'm not sure why this check for `node_modules` already existing was there. Since `install_or_update` only runs when `needs_installation` decided that it needs to be installed, it seems to make sense to do it unconditionally. But I might be forgetting some case that it optimized...
@predragnikolic this is likely the reason you had similar issue before with server not updating.
=> fix npm install not running when local node_modules exists

st3/lsp_utils/node_runtime.py, st3/lsp_utils/server_npm_resource.py
Previously there were many cases where the errors were confusing (#80, #92). Now it should be better as we'll print a nice log detailing what failed and what didn't meet expectations regarding Node.js.
(the code needs some refactoring but I have no resources for that right now)
=> Improve messaging on errors with Node.js and version resolving

README.md, lsp_utils.sublime-settings, st3/lsp_utils/__init__.py, st3/lsp_utils/constants.py, st3/lsp_utils/node_runtime.py, st3/lsp_utils/npm_client_handler.py, st3/lsp_utils/server_npm_resource.py, sublime-package.json, tests/setup.py, tests/test_smoketest.py
Since electron builds have [pointer compression](https://v8.dev/blog/pointer-compression) enabled, those use quite a bit less memory than the official Node.js builds.
I haven't been able to find official Node.js builds with pointer compression enabled so using Electron itself is the next best thing and is easiest to handle since those can be installed as a NPM dependency.
Electron binary is fairly big itself (about 200MB on Mac, compared to about 100MB for Node.js) since it contains fair amount of extra stuff besides just Node.js build but it's not relevant for memory usage at runtime.
For reference, on Mac, the LSP-typescript running on a VSCode repo with a bunch of files opened uses following amounts of memory:
- 210MB when running on the official Node.js build
- 142MB when running on …
=> Allow use of electron runtime for Node-based servers

st3/lsp_utils/helpers.py, st3/lsp_utils/node_runtime.py
On some "broken" Windows installations, running subprocess with shell=True can result in error exit code being returned from "node --version" even though node itself completes successfully.
This was reported few times and one time the culprit was an AutuRun script that made non-interactive shell executions result in exiting with error code.
Since our paths are fully resolved with shutil.which, we shouldn't need the side effect of shell=True that makes PATH being inherited from the system.
Fixes #100
=> fix(node): improve handling on "broken" Windows installations

st3/lsp_utils/node_runtime.py
This PR...
1. updates NodeJS to 18.18.1
2. updates Electron to 26.4.0
=> feat: update local nodejs and electron runtimes to v18

st3/lsp_utils/node_runtime.py, st3/lsp_utils/server_npm_resource.py
The package storage for a given LSP-* package will essentially get all subdirectories removed on installing a new version of the server so the cleanup will be done on starting particular servers rather than everything at once.
Resolves #90
=> fix(node): cleanup storage for no longer used servers and runtimes

st3/lsp_utils/generic_client_handler.py, st3/lsp_utils/helpers.py, st3/lsp_utils/node_runtime.py, st3/lsp_utils/server_npm_resource.py, st3/lsp_utils/server_pip_resource.py
Resolves https://github.com/sublimelsp/lsp_utils/issues/109
That deletion shouldn't in the try...catch block because its exception is not for ` * Failed downloading: ...` but due to locked files. This is quite confusing in the error log.
`ignore_errors=True` for `shutil.rmtree()` is being added too so that at least the whole procedure can go on (install runtime, invoke servers etc).
=> fix: deleting old runtime shouldn't emit an exception

st3/lsp_utils/pip_client_handler.py
Related to https://github.com/sublimelsp/LSP-pylsp/issues/125
=> fix(pip): improve error on python binary not being present

st3/lsp_utils/_client_handler/abstract_plugin.py, st3/lsp_utils/helpers.py
`configuration.env['PATH']` is bound to a server class and we just keep prepending the same additional paths into it every time when there is a new session starts (e.g., a project is opened in a new window). Eventually, it triggers this bug: https://github.com/TerminalFi/LSP-copilot/issues/163
=> fix: additional paths shouldn't be duplicated every time a new session starts

st3/lsp_utils/generic_client_handler.py
This change refactors the package control dependency to be optional by catching the import error if package control is not available and making it an no-op operation.
Previously the import error at the top prevented LSP utils from working properly when package control was not available.
=> fix: package control can be an optional dependency

st3/lsp_utils/_client_handler/interface.py, st3/lsp_utils/generic_client_handler.py
Those are not optional. I think the reason it was like that was to support the legacy interface that is now removed.
=> fix: update optionality of the is_allowed_to_start() method

st3/lsp_utils/pip_client_handler.py, tests/test_smoketest.py
I'm probably not gonna test it myself. If someone is able then please do and report back.
Resolves #121
=> fix: switch to `py` for running python on Windows

st4_py38/lsp_utils/pip_client_handler.py
=> fix: fallback to "python" binary on Windows
